/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alex_ts_parser_native_function_NativeFunctionManager */

#ifndef _Included_com_alex_ts_parser_native_function_NativeFunctionManager
#define _Included_com_alex_ts_parser_native_function_NativeFunctionManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseTSFileNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseTSFileNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseAge
 * Signature: ()Lcom/alex/ts_parser/bean/psi/TestClass;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseAge
  (JNIEnv *, jclass);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parsePAT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/psi/PAT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parsePAT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseCAT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/psi/CAT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseCAT
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
