/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alex_ts_parser_native_function_NativeFunctionManager */

#ifndef _Included_com_alex_ts_parser_native_function_NativeFunctionManager
#define _Included_com_alex_ts_parser_native_function_NativeFunctionManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseTSFileNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseTSFileNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseAge
 * Signature: ()Lcom/alex/ts_parser/bean/psi/TestClass;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseAge
  (JNIEnv *, jclass);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parsePAT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/psi/PAT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parsePAT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseCAT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/psi/CAT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseCAT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseNIT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/psi/NIT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseNIT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parsePMT
 * Signature: (Ljava/lang/String;I[Lcom/alex/ts_parser/bean/psi/PAT_ProgramInfo;)[Lcom/alex/ts_parser/bean/psi/PMT_Table;
 */
JNIEXPORT jobjectArray JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parsePMT
  (JNIEnv *, jclass, jstring, jint, jobjectArray);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseTOT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/TOT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseTOT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseTDT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/TDT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseTDT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseSDT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/SDT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseSDT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseBAT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/BAT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseBAT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseDIT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/DIT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseDIT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseEIT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/EIT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseEIT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseRST
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/RST_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseRST
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseST
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/ST_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseST
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alex_ts_parser_native_function_NativeFunctionManager
 * Method:    parseSIT
 * Signature: (Ljava/lang/String;)Lcom/alex/ts_parser/bean/si/SIT_Table;
 */
JNIEXPORT jobject JNICALL Java_com_alex_ts_1parser_native_1function_NativeFunctionManager_parseSIT
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
