/*
 * DescriptorTag.h
 *
 *  Created on: 2017Äê9ÔÂ7ÈÕ
 *      Author: Administrator
 */

#ifndef _DESCRIPTORTAG_H_
#define _DESCRIPTORTAG_H_

#define VIDEO_STREAM_DESCRIPTOR_TAG 0x02
#define AUDIO_STREAM_DESCRIPTOR_TAG 0x03
#define DATA_STREAM_ALIGNMENT_DESCRIPTOR_TAG 0x06
#define CA_DESCRIPTOR_TAG 0x09
#define ISO_639_LANGUAGE_DESCRIPTOR_TAG 0x0a
#define SYSTEM_CLOCK_DESCRIPTOR_TAG 0X0b
#define MAXIMUM_BITRATE_DESCRIPTOR_TAG 0x0e

#define NETWORK_NAME_DESCRIPTOR_TAG 0x40
#define SERVICE_LIST_DESCRIPTOR_TAG 0x41
#define SATELLITE_DELIVERY_SYSTEM_DESCRIPTOR_TAG 0x43
#define CABLE_DELIVERY_SYSTEM_DESCRIPTOR_TAG 0x44
#define BOUQUET_NAME_DESCRIPTOR_TAG 0x47
#define SERVICE_DESCRIPTOR_TAG 0x48
#define LINKAGE_DESCRIPTOR_TAG 0x4a
#define SHORT_EVENT_DESCRIPTOR_TAG 0x4d
#define EXTENDED_EVENT_DESCRIPTOR_TAG 0x4e
#define STREAM_IDENTIFIER_DESCRIPTOR_TAG 0x52
#define TELETEXT_DESCRIPTOR_TAG 0x56
#define LOCAL_TIME_OFFSET_DESCRIPTOR_TAG 0x58
#define SUBTITLING_DESCRIPTOR_TAG 0x59
#define TERRESTRIAL_DELIVERY_SYSTEM_DESCRIPTOR_TAG 0x5a
#define FREQUENCY_LIST_DESCRIPTOR_TAG 0x62

#endif /* DESCRIPTORTAG_H_ */
